# Generated by Django 4.2.29 on 2026-03-11 08:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_remove_listing_image_url_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
